# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta

jobs:
  lint:
    name: Lint
    runs-on: ci-general
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest &&
          $HOME/go/bin/staticcheck && make vet

  test:
     runs-on: ci-general
     strategy:
       matrix:
         go:
           - "1.19"
           - "1.18"
     name: "Test: go v${{ matrix.go }}"
     steps:
       - uses: actions/checkout@v2
       - name: Setup go
         uses: actions/setup-go@v1
         with:
           go-version: ${{ matrix.go }}
       - name: Test
         run: make test
       - name: Coveralls
         run: make coverage && make coveralls
         if: matrix.go == '1.18'
         env:
           COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           COVERALLS_FLAG_NAME: Go-${{ matrix.go }}
